apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: repo-name
      value: $(body.repository.name)
    - name: commit-sha
      value: $(body.after)
    - name: branch
      value: $(body.ref)
    - name: context-dir
      value: "."
