quarkus:
  banner:
    enabled: false
  http:
    port: 8080
  smallrye-openapi:
    info-title: Hello World API
    info-version: 1.0.0
    info-description: A simple Hello World REST API

"%dev":
  quarkus:
    http:
      port: 8080

"%test":
  quarkus:
    http:
      port: 8081

"%prod":
  quarkus:
    http:
      port: 8080
