apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml          # sync-wave-0
  - operator-group.yaml     # sync-wave-1
  - subscription.yaml       # sync-wave-2
